services:
  web:
    image: oceanpact/web
    build: docker/web
    ports:
      - "${OCEANPACT_HTTP_PORT:-8090}:80"
      - "${OCEANPACT_HTTPS_PORT:-4430}:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "$PWD/docker/web/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/docker/web/templates:/etc/nginx/http.d"
      - "$PWD/docker/web/tls:/etc/nginx/tls"
      - "$PWD/public:/app/public"
    tty: true
    networks:
      oceanpact-net:
        aliases:
          - oceanpact.test

  oceanpact.test:
    image: oceanpact/oceanpact.test:latest
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - "${HOME}/.ssh:/home/php/.ssh"
      - "$PWD:/app"
    working_dir: /app
    tty: true
    environment:
      - IDE_KEY=${IDE_KEY:-docker}
      - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
    networks:
      - oceanpact-net

  redis:
    image: redis:alpine
    volumes:
      - "oceanpact-data-redis:/data"
    networks:
      - oceanpact-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  mailpit:
    image: "axllent/mailpit"
    ports:
      - "${OCEANPACT_MAILPIT_API_PORT:-1026}:1025"
      - "${OCEANPACT_MAILPIT_UI_PORT:-8026}:8025"
    networks:
      - oceanpact-net

  mysql:
    image: mysql:8
    ports:
      - "${OCEANPACT_DB_PORT:-3308}:3306"
    volumes:
      - "oceanpact-data-mysql:/var/lib/mysql"
    networks:
      - oceanpact-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_DATABASE=${DB_DATABASE:-oceanpact}
      - MYSQL_USER=${DB_USERNAME:-oceanpact}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}

  mysql-testing:
    image: mysql:8
    ports:
      - "${OCEANPACT_DB_TEST_PORT:-3309}:3306"
    networks:
      - oceanpact-net
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-oceanpact}
      - MYSQL_USER=${DB_USERNAME:-oceanpact}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - "oceanpact-data-mysql-testing:/var/lib/mysql"

networks:
  oceanpact-net:
    driver: "bridge"

volumes:
  oceanpact-data-redis:
    driver: local
  oceanpact-data-mysql:
    driver: local
  oceanpact-data-mysql-testing:
    driver: local
