version: '3'
services:
    web:
        image: oceanpact/web
        build: docker/web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "$PWD/docker/web/nginx.conf:/etc/nginx/nginx.conf"
            - "$PWD/docker/web/templates:/etc/nginx/http.d"
            - "$PWD/docker/web/tls:/etc/nginx/tls"
            - "$PWD/public:/app/public"
        tty: true
        networks:
            - oceanpact-net

    app:
        image: oceanpact/app
        build: docker/php
        volumes:
            - "$PWD/docker/php/php-fpm:/php-fpm"
            - "$PWD/docker/php/conf/php.ini:/etc/php82/php.ini"
            - "$PWD/docker/php/conf/php-fpm.d/www.conf:/etc/php82/php-fpm.d/www.conf"
            - "$PWD/docker/php/conf/conf.d/50_xdebug.ini:/etc/php82/conf.d/50_xdebug.ini"
            - "$PWD:/app"
        working_dir: /app
        tty: true
        environment:
            - IDE_KEY=${IDE_KEY:-docker}
            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
            - XDEBUG_MODE=${XDEBUG_MODE:-off}
        networks:
            - oceanpact-net

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - "oceanpact-data-redis:/data"
        networks:
            - oceanpact-net
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

    mailpit:
        image: "axllent/mailpit"
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - oceanpact-net

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - "oceanpact-data-mysql:/var/lib/mysql"
        networks:
            - oceanpact-net
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
            - MYSQL_DATABASE=${DB_DATABASE:-oceanpact}
            - MYSQL_USER=${DB_USERNAME:-oceanpact}

networks:
    oceanpact-net:
        driver: "bridge"

volumes:
    oceanpact-data-redis:
        driver: local
    oceanpact-data-mysql:
        driver: local
