version: '3'

services:
  oceanpact.dev:
    image: ocean-pact/php-nginx-local:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${HOME}/.ssh:/home/php/.ssh"
      - "$PWD:/var/www/html"
    working_dir: /var/www/html
    tty: true
    depends_on:
      - mysql
      - redis
      - mailpit
      - mysql-testing
    environment:
      - IDE_KEY=${IDE_KEY:-docker}
      - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
    networks:
      - oceanpact-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "oceanpact-data-redis:/data"
    networks:
      - oceanpact-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  mailpit:
    image: "axllent/mailpit"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - oceanpact-net

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - "oceanpact-data-mysql:/var/lib/mysql"
    networks:
      - oceanpact-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_DATABASE=${DB_DATABASE:-oceanpact}
      - MYSQL_USER=${DB_USERNAME:-oceanpact}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}

  mysql-testing:
    image: mysql:8
    ports:
      - "3307:3306"
    networks:
      - oceanpact-net
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - "oceanpact-data-mysql-testing:/var/lib/mysql"

  node:
    image: node:18-alpine
    volumes:
      - "$PWD:/app"
    working_dir: /app
    tty: true
    networks:
      - oceanpact-net

networks:
  oceanpact-net:
    driver: "bridge"

volumes:
  oceanpact-data-redis:
    driver: local
  oceanpact-data-mysql:
    driver: local
  oceanpact-data-mysql-testing:
    driver: local
