FROM ocean-pact/php-nginx-base:latest

# Temporary switch to root
USER root

# Install xdebug
RUN apk add --no-cache mysql-client mariadb-connector-c php83-pecl-xdebug

# Add configuration
COPY docker/php-nginx/config/conf.d/50_xdebug.ini ${PHP_INI_DIR}/conf.d/50_xdebug.ini

# Install composer from the official image
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Switch back to non-root user
USER nobody

COPY docker/php-nginx/config/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY cert.pem /etc/nginx/tls/cert.pem
COPY key.pem /etc/nginx/tls/key.pem
