version: '3'
services:
    web:
        image: ocean-pact:web
        build: docker/web
        depends_on:
            - app
        ports:
            - '88:80'
            - '8443:443'
        volumes:
            - "$PWD/docker/web/nginx.conf:/etc/nginx/nginx.conf"
            - "$PWD/docker/web/templates:/etc/nginx/http.d"
            - "$PWD/docker/web/tls:/etc/nginx/tls"
            - "$PWD/public:/app/public"
            - "$PWD/storage/app:/app/storage/app"
        tty: true
        networks:
            - ocean-pact

    app:
        image: ocean-pact:app
        build: docker/php
        volumes:
            - "$PWD/docker/php/php-fpm:/php-fpm"
            - "$PWD/docker/php/conf/php.ini:/etc/php81/php.ini"
            - "$PWD/docker/php/conf/php-fpm.d/www.conf:/etc/php81/php-fpm.d/www.conf"
            - "$PWD/docker/php/conf/conf.d/50_xdebug.ini:/etc/php81/conf.d/50_xdebug.ini"
            - "$PWD:/app"
#        ports:
#            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            IDE_KEY: '${IDE_KEY:-docker}'
            XDEBUG_CLIENT_HOST: '${XDEBUG_CLIENT_HOST:-host.docker.internal}'
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
        tty: true
        networks:
            - ocean-pact
        extra_hosts:
            - "ocean-pact.test:172.17.0.1"
            - "host.docker.internal:host-gateway"
        depends_on:
            - mysql
            - redis
            - mailhog

    mysql:
        image: 'mysql:8'
        ports:
            - '${FORWARD_DB_PORT:-8306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'ocean-pact-mysql:/var/lib/mysql'
        networks:
            - ocean-pact
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-8379}:6379'
        volumes:
            - 'ocean-pact-redis:/data'
        networks:
            - ocean-pact
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1026}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8026}:8025'
        networks:
            - ocean-pact
networks:
    ocean-pact:
        driver: bridge
volumes:
    ocean-pact-mysql:
        driver: local
    ocean-pact-redis:
        driver: local
    ocean-pact-meilisearch:
        driver: local
